FROM python:3.10-slim

# Đặt thư mục làm việc là /frontend
WORKDIR /frontend

# Sao chép tất cả các tệp và thư mục trừ src
COPY ./src/gui/gui.py /frontend/gui.py
# Bạn có thể thêm các thư mục hoặc tệp cần thiết riêng lẻ
# COPY ./other_dir /frontend/other_dir

# Cài đặt các dependencies
RUN pip install streamlit

# Cài đặt gói để đọc định dạng docx và PDF
RUN pip install docx2txt PyMuPDF

# Mở port 8501
EXPOSE 8501

# Đặt entrypoint để chạy Streamlit
ENTRYPOINT ["streamlit", "run", "gui.py"]