FROM python:3.10-slim

# Đặt thư mục làm việc là /backend
WORKDIR /backend

# Copy toàn bộ nội dung từ thư mục cha vào /app trong container
COPY . .

# Cài đặt các dependencies
RUN pip install -r requirements.txt

WORKDIR /backend/src

# Mở port 5005
EXPOSE 5005

# Đặt entrypoint
ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5005", "--reload"]